healthy_subs = {
	'butter':'olive oil',
	'white sugar':'brown sugar',
	'powdered sugar':'brown sugar',
	'maple syrup':'honey',
	'granulated sugar':'brown sugar',
	'spam':'lean turkey',
	'corned beef':'lean turkey',
	'bacon':'seitan',
	'sausage':'lean turkey',
	'beef':'lean turkey',
	'chicken':'lean turkey',
	'pork':'lean turkey',
	'lamb':'lean turkey',
	'white rice':'quinoa',
	'potato':'squash',
	'white bread':'whole-wheat bread',
	'egg':'tablespoon mung bean paste',
	'eggs':'tablespoons mung bean paste',
	'egg white':'aquafaba',
	'margarine':'olive oil',
	'condensed milk':'milk',
	'mayonnaise':'avocado',
	'milk chocolate':'dark chocolate',
	'MSG':'garlic',
	'vegetable shortening':'coconut oil',
	'shortening':'coconut oil',
	'white flour':'whole wheat flour',
	'soy sauce':'sesame oil',
	'hoison sauce':'sesame oil',
	'cream cheese':'cottage cheese',
	'heavy cream':'cottage cheese',
	'spaghetti':'zoodles',
	'linguine':'zoodles',
	'fettucine':'zoodles',
	'vermicelli':'zoodles',
	'tagliatelle':'zoodles',
	'rigatoni':'zucchini pasta',
	'macaroni':'zucchini pasta',
	'penne':'zucchini pasta',
	'cavatappi':'zucchini pasta',
	'farfelle':'zucchini pasta',
	'ranch':'vinaigrette',
	'caesar dressing':'vinaigrette',
	'anchovies':'sun dried tomatoes',
	'Dijon mustard':'vinaigrette',
	'croutons':'wasabi peas',
	'plain yogurt':'greek yogurt',
	'shredded mozzarella':'greek yogurt'

}

unhealthy_subs = {
	'vegetable oil':'butter',
	'olive oil':'butter',
	'canola oil':'butter',
	'avocado oil':'butter',
	'sesame oil':'butter',
	'couscous':'white rice',
	'brown rice':'white rice',
	'quinoa':'white rice',
	'zoodles':'spaghetti',
	'squash':'potato',
	'vinaigrette':'caesar dressing',
	'dark chocolate':'milk chocolate',
	'ground turkey':'ground beef',
	'turkey':'chicken',
	'tofu':'chicken',
	'aquafaba':'egg',
	'seitan':'bacon',
	'turkey bacon':'bacon',
	'shiitake mushroom':'chicken',
	'honey':'maple syrup',
	'brown sugar':'white sugar',
	'kale':'lettuce',
	'cauliflower rice':'white rice',
	'oats':'white rice',
	'whole-wheat bread':'white bread',
	'greek yogurt':'plain yogurt'
}